import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/component/Navbar/Navbar'
import Footer from '@/component/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sahad',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme="forest" lang="en">
      <body  className={inter.className}>
          <div className=' w-[80%] mx-auto'>
          <Navbar />
          {children}
          <Footer />
          </div>
        </body>
    </html>
  )
}
